# Generated by Django 5.1.5 on 2025-02-03 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_on', models.DateTimeField(auto_created=True)),
                ('task_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_descriptioon', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
