# Generated by Django 5.1.5 on 2025-02-03 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2025, 2, 3, 9, 10, 20, 308367)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
